on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.20'
          - '1.21'
          - '1.22'
          - '1.23'
    name: Go v${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - run: make test-go
